name: Build

on: [ push ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: Windows Mingw-w64 ${{ matrix.config.name }}
    runs-on: windows-latest

    strategy:
      matrix:
        config:
          - {
            name: "GCC",
            cc: "C:/msys64/mingw64/bin/gcc.exe",
            cxx: "C:/msys64/mingw64/bin/g++.exe"
          }
          - {
            name: "Clang",
            cc: "C:/msys64/mingw64/bin/clang.exe",
            cxx: "C:/msys64/mingw64/bin/clang++.exe"
          }

    env:
      CC: ${{ matrix.config.cc }}
      CXX: ${{ matrix.config.cxx }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Submodules
        run: git submodule update --init --recursive

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=$BUILD_TYPE $GITHUB_WORKSPACE

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Run Tests
        working-directory: ${{github.workspace}}/build
        shell: bash
        run: ./OnitamaTests.exe